### PR TITLE
Adds docker CouchDB to run integration tests

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Refactors the recursive function to not pass many parameters multiple times. 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or integration tests where appropriate
- Backwards compatible: Works with existing data and configuration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
@njogz what do you think?

**Review by njogz — CHANGES_REQUESTED** [review]
Great job on this! I like the refactor you have done to the moveReports function. Just one request; Can we add a test where the batch size is larger than the number of reports?

**Comment by dianabarsan** [comment]
> Can we add a test where the batch size is larger than the number of reports?

I think that all the other integration tests in the suite already cover that (where we don't manipulate the batch size).

**Comment by njogz** [comment]
Great point! Approved.

**Review by njogz — APPROVED** [review]

**Comment by dianabarsan** [comment]
hey @njogz 
I pushed 2 commits, one to explicitly reset the batch size after the batching tests - so we make sure the other integration tests are running with the default batch size. The other one is to add a comment about why we use remote Couch and updates the readme to mention that tests need Docker. 

Is this still alright with you? 
Thanks!

**Comment by njogz** [comment]
@dianabarsan Yes, that is perfectly fine. Thanks.

**Pull request merged**
