### PR TITLE
458 - Process exit code consistency - 0=success 1=failure

### PR DESCRIPTION
**Pull request by kennsippell**
# Description

#458

The current process exit code indicating failure is slightly inconsistent: a mix of 1,-1,or false. 
Returning false actually ends up being the numeric 0 -- which indicates success.

This change standardizes to `-1` for all failure and `0` for all success.

For testing the fix for #458, I ran `node src/bin --url=https://broken.broken backup-all-forms` and then `echo $?`.  Before the change it is 0, after it is 255 (-1).

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or integration tests where appropriate
- Backwards compatible: Works with existing data and configuration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by garethbowen — COMMENTED** [review]
Thanks @kennsippell - definitely an improvement.

Returning a negative number isn't very common so I think it'd be better to standardise on `1` instead. What do you think?

**Comment by kennsippell** [comment]
@garethbowen I've made that change.

Personally, I find the difference in expectation of _exit codes vs booleans_ to be a bit confusing sometimes. 0 is success for an exit code and fail for a boolean. It is enough that then I'm reading code, I have to stop and think. 

I personally prefer `-1` or something "more weird than 1" for failures.

**Comment by garethbowen** [comment]
@kennsippell Makes sense. Certainly the code could be more readable. One thing I would be looking at if I were refactoring this code is separating the logic from the exit code work. For example, extract that whole function and return a boolean for success/fail, then have the smallest possible function just invoke that code and exit with the appropriate error code. But that's a job for another day - getting them all consistent is a big win, thanks!

**Review by garethbowen — APPROVED** [review]
Thanks! LGTM.

Is this ready for AT?

**Comment by kennsippell** [comment]
> Is this ready for AT?

Ya!

**Pull request merged**
